/**
 * PDF-export stories — framework-free usage examples for the Gantt **paginated
 * PDF export** feature, used by the docs app and as a canonical reference. Each
 * story mounts a `Gantt` with the PDF-export feature installed and an accessible
 * "Export PDF" trigger button that drives `gantt.exportPdf(...)`.
 */
import { Gantt } from '../ui/gantt.js';
import { installPdfExport, type GanttWithPdfExport } from './gantt-pdf-export.js';
import type { GanttPdfExportOptions } from './pdf.js';
import type { TaskModel, DependencyModel } from '../contract.js';
import './pdf.css';

export interface Story {
  name: string;
  render: (host: HTMLElement) => Gantt;
}

const DAY = 86_400_000;
const T0 = Date.UTC(2026, 0, 5);

function plan(): { tasks: TaskModel[]; dependencies: DependencyModel[] } {
  const tasks: TaskModel[] = [
    { id: 'p', name: 'Release 1.0' },
    { id: 'a', name: 'Design', parentId: 'p', start: T0, duration: 5 * DAY, end: T0 + 5 * DAY } as TaskModel,
    { id: 'b', name: 'Build', parentId: 'p', start: T0 + 5 * DAY, duration: 8 * DAY, end: T0 + 13 * DAY, percentDone: 0.4 } as TaskModel,
    { id: 'c', name: 'Test', parentId: 'p', start: T0 + 13 * DAY, duration: 4 * DAY, end: T0 + 17 * DAY } as TaskModel,
    { id: 'm', name: 'Launch', parentId: 'p', start: T0 + 17 * DAY, milestone: true } as TaskModel,
  ];
  const dependencies: DependencyModel[] = [
    { id: 'l1', fromId: 'a', toId: 'b', type: 'FS' },
    { id: 'l2', fromId: 'b', toId: 'c', type: 'FS' },
  ];
  return { tasks, dependencies };
}

/** Mount a Gantt + an Export-PDF toolbar button wired to the given options. */
function mountWithExport(
  host: HTMLElement,
  exportOpts: GanttPdfExportOptions,
): Gantt {
  const { tasks, dependencies } = plan();

  const toolbar = document.createElement('div');
  toolbar.className = 'jects-gantt-pdf-toolbar';
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'jects-gantt-pdf-export-btn';
  btn.textContent = 'Export PDF';
  toolbar.appendChild(btn);

  const chart = document.createElement('div');
  chart.style.height = '420px';

  host.append(toolbar, chart);

  const gantt: GanttWithPdfExport = installPdfExport(
    new Gantt(chart, { tasks, dependencies, projectStart: T0 }),
  );

  btn.addEventListener('click', () => {
    void gantt.exportPdf({ ...exportOpts, download: 'gantt-plan.pdf' });
  });

  return gantt as unknown as Gantt;
}

export const stories: Story[] = [
  {
    name: 'A4 landscape, fit-to-width, with header + page footer',
    render: (host) =>
      mountWithExport(host, {
        page: 'A4',
        orientation: 'landscape',
        fitToWidth: true,
        title: 'Release 1.0 — Project Plan',
        header: { left: 'Release 1.0', right: 'Confidential' },
        footer: { center: 'Page {page} of {pages}' },
      }),
  },
  {
    name: 'Letter portrait, fixed 1:1 scale (tile across pages)',
    render: (host) =>
      mountWithExport(host, {
        page: 'Letter',
        orientation: 'portrait',
        fitToWidth: false,
        scale: 1,
        title: 'Release 1.0',
        footer: { left: 'Generated by Jects UI', right: '{page}/{pages}' },
      }),
  },
];
