/**
 * @jects/theme — runtime theme helpers.
 *
 * The CSS contract is generated by `scripts/build-theme.mjs` into `dist/css/*`.
 * This module provides imperative helpers to switch themes and apply per-scope
 * token overrides at runtime (the same contract the customizer writes).
 */

// Bundle the base stylesheet into the package's emitted `dist/style.css`
// so consumers can `import '@jects/theme/style.css'`.
import './theme.css';

import {
  TOKEN_PREFIX,
  LIGHT_DEFAULTS,
  DARK_DEFAULTS,
  type JectsSemanticName,
} from '@jects/tokens';

export type ThemeName =
  | 'light'
  | 'dark'
  | 'light-hc'
  | 'dark-hc'
  | 'stockholm'
  | 'material';

/** Per-scope override map. Semantic names map to OKLCH triplets; scalars (radius) to CSS values. */
export interface ThemeOverrides {
  primary?: string;
  'primary-foreground'?: string;
  background?: string;
  foreground?: string;
  accent?: string;
  border?: string;
  ring?: string;
  radius?: string;
  'font-family'?: string;
  /** Any other token name → value. */
  [token: string]: string | undefined;
}

const THEME_ATTR = 'data-jects-theme';

/**
 * Set the active theme on a scope element (default `<html>`). Toggles the
 * `data-jects-theme` attribute and the convenience `.jects-dark`/`.jects-hc`
 * classes the generated CSS keys off.
 */
export function setTheme(name: ThemeName, scope: HTMLElement = document.documentElement): void {
  scope.setAttribute(THEME_ATTR, name);
  const dark = name === 'dark' || name === 'dark-hc';
  const hc = name === 'light-hc' || name === 'dark-hc';
  scope.classList.toggle('jects-dark', dark);
  scope.classList.toggle('jects-hc', hc);
  scope.classList.toggle('jects-theme-stockholm', name === 'stockholm');
  scope.classList.toggle('jects-theme-material', name === 'material');
}

/** Read the active theme name from a scope element. */
export function getTheme(scope: HTMLElement = document.documentElement): ThemeName {
  return (scope.getAttribute(THEME_ATTR) as ThemeName) ?? 'light';
}

/**
 * Apply per-scope token overrides as inline CSS custom properties. This is the
 * runtime theming primitive the customizer uses. Values are written verbatim,
 * so pass OKLCH triplets for color tokens (e.g. `'0.6 0.2 265'`).
 */
export function applyTheme(scope: HTMLElement, overrides: ThemeOverrides): void {
  for (const [name, value] of Object.entries(overrides)) {
    if (value === undefined) continue;
    scope.style.setProperty(`${TOKEN_PREFIX}${name}`, value);
  }
}

/** Remove previously-applied inline overrides for the given token names (or all known semantic tokens). */
export function clearTheme(scope: HTMLElement, names?: string[]): void {
  const list = names ?? Object.keys(LIGHT_DEFAULTS);
  for (const name of list) scope.style.removeProperty(`${TOKEN_PREFIX}${name}`);
}

/**
 * Serialize the current effective values of `names` (default: all semantic tokens)
 * on `scope` into a `:root { ... }` stylesheet string — the "Export theme.css" payload.
 */
export function exportThemeCss(
  scope: HTMLElement = document.documentElement,
  names: string[] = Object.keys(LIGHT_DEFAULTS),
  selector = ':root',
): string {
  const styles = getComputedStyle(scope);
  const lines = names
    .map((name) => {
      const value = styles.getPropertyValue(`${TOKEN_PREFIX}${name}`).trim();
      return value ? `  ${TOKEN_PREFIX}${name}: ${value};` : null;
    })
    .filter((l): l is string => l !== null);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

export { LIGHT_DEFAULTS, DARK_DEFAULTS, TOKEN_PREFIX, type JectsSemanticName };
