// Custom token build: JSON source of truth -> CSS custom properties, SCSS maps, TS types.
// Kept deliberately small (no Style Dictionary dependency). Run via `pnpm build`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'src/tokens.json'), 'utf8'));

const PREFIX = '--jects-';
mkdirSync(resolve(root, 'dist'), { recursive: true });
mkdirSync(resolve(root, 'dist-src'), { recursive: true });

/** Prefix the CMYK group so emitted names are --jects-cmyk-cyan, etc. */
const cmykPrefixed = Object.fromEntries(
  Object.entries(tokens.cmyk).map(([k, v]) => [`cmyk-${k}`, v]),
);

/** All Tier-2 semantic + scale + cmyk + data token names (the stable public name set). */
const semanticNames = Object.keys(tokens.semantic.light);
const scaleNames = Object.keys(tokens.scale);
const cmykNames = Object.keys(cmykPrefixed);
const dataNames = Object.keys(tokens.data);
const allNames = [...semanticNames, ...cmykNames, ...dataNames, ...scaleNames];

function declBlock(map, indent = '  ') {
  return Object.entries(map)
    .map(([k, v]) => `${indent}${PREFIX}${k}: ${v};`)
    .join('\n');
}

// ---- CSS ------------------------------------------------------------------
// Tier-2 light defaults on :root, plus cmyk/data/scale (theme-invariant) here too.
const css = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit. */
/* Jects UI tokens — House style: ${tokens.$meta.name}. */
/* OKLCH channel triplets \`L C H\`; consume as oklch(var(${PREFIX}x)). */

:root {
  /* Tier-2 semantic (light) */
${declBlock(tokens.semantic.light)}

  /* Calm CMYK categorical palette */
${declBlock(cmykPrefixed)}

  /* Chart series ramp (built from CMYK order) */
${declBlock(tokens.data)}

  /* Scales (theme-invariant) */
${declBlock(tokens.scale)}
}
`;
writeFileSync(resolve(root, 'dist/tokens.css'), css);

// ---- SCSS maps ------------------------------------------------------------
function scssMap(name, map) {
  const entries = Object.entries(map)
    .map(([k, v]) => `  '${k}': (${typeof v === 'string' && v.includes(',') ? `'${v}'` : v}),`)
    .join('\n');
  return `$jects-${name}: (\n${entries}\n);\n`;
}
const scss = `// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit.
// Authoring-only SCSS maps. The runtime contract is CSS custom properties.
${scssMap('semantic-light', tokens.semantic.light)}
${scssMap('semantic-dark', tokens.semantic.dark)}
${scssMap('cmyk', cmykPrefixed)}
${scssMap('data', tokens.data)}
${scssMap('scale', tokens.scale)}
@function jects-var($name) {
  @return var(#{'${PREFIX}'}#{$name});
}
`;
writeFileSync(resolve(root, 'dist/tokens.scss'), scss);

// ---- TS source (compiled by tsc into dist/index.js + .d.ts) ---------------
const union = allNames.map((n) => `  | '${PREFIX}${n}'`).join('\n');
const ts = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit. */
/** Every Jects token CSS custom-property name (prefixed). */
export type JectsTokenName =
${union};

/** Tier-2 semantic token names (without prefix). */
export type JectsSemanticName =
${semanticNames.map((n) => `  | '${n}'`).join('\n')};

/** Calm CMYK palette token names (without prefix). */
export type JectsCmykName =
${cmykNames.map((n) => `  | '${n}'`).join('\n')};

/** Scale/scalar token names (without prefix). */
export type JectsScaleName =
${scaleNames.map((n) => `  | '${n}'`).join('\n')};

/** The CSS custom-property prefix used by every token. */
export const TOKEN_PREFIX = '${PREFIX}' as const;

/** All Tier-2 semantic names. */
export const SEMANTIC_TOKENS = ${JSON.stringify(semanticNames)} as const;

/** Calm CMYK categorical palette names. */
export const CMYK_TOKENS = ${JSON.stringify(cmykNames)} as const;

/** Chart series ramp names (data-1 … data-8). */
export const DATA_TOKENS = ${JSON.stringify(dataNames)} as const;

/** Scale token names. */
export const SCALE_TOKENS = ${JSON.stringify(scaleNames)} as const;

/** Default (light) OKLCH triplet values for the house theme. */
export const LIGHT_DEFAULTS: Record<string, string> = ${JSON.stringify(tokens.semantic.light, null, 2)};

/** Dark OKLCH triplet values for the house theme. */
export const DARK_DEFAULTS: Record<string, string> = ${JSON.stringify(tokens.semantic.dark, null, 2)};

/** Build a token reference, e.g. tokenVar('primary') => 'var(--jects-primary)'. */
export function tokenVar(name: string): string {
  return \`var(\${TOKEN_PREFIX}\${name})\`;
}

/** Build an oklch() color from a triplet token, e.g. oklch('primary', 0.5). */
export function oklchToken(name: string, alpha?: number): string {
  const ref = tokenVar(name);
  return alpha === undefined ? \`oklch(\${ref})\` : \`oklch(\${ref} / \${alpha})\`;
}
`;
writeFileSync(resolve(root, 'dist-src/index.ts'), ts);

console.log(
  `tokens: wrote ${allNames.length} names -> dist/tokens.css, dist/tokens.scss, dist-src/index.ts`,
);
