/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit. */
/** Every Jects token CSS custom-property name (prefixed). */
export type JectsTokenName =
  | '--jects-background'
  | '--jects-foreground'
  | '--jects-card'
  | '--jects-card-foreground'
  | '--jects-popover'
  | '--jects-popover-foreground'
  | '--jects-primary'
  | '--jects-primary-foreground'
  | '--jects-secondary'
  | '--jects-secondary-foreground'
  | '--jects-muted'
  | '--jects-muted-foreground'
  | '--jects-accent'
  | '--jects-accent-foreground'
  | '--jects-destructive'
  | '--jects-destructive-foreground'
  | '--jects-success'
  | '--jects-success-foreground'
  | '--jects-warning'
  | '--jects-warning-foreground'
  | '--jects-border'
  | '--jects-input'
  | '--jects-ring'
  | '--jects-cmyk-cyan'
  | '--jects-cmyk-magenta'
  | '--jects-cmyk-yellow'
  | '--jects-cmyk-key'
  | '--jects-cmyk-cyan-soft'
  | '--jects-cmyk-magenta-soft'
  | '--jects-cmyk-yellow-soft'
  | '--jects-cmyk-key-soft'
  | '--jects-data-1'
  | '--jects-data-2'
  | '--jects-data-3'
  | '--jects-data-4'
  | '--jects-data-5'
  | '--jects-data-6'
  | '--jects-data-7'
  | '--jects-data-8'
  | '--jects-space-0'
  | '--jects-space-1'
  | '--jects-space-2'
  | '--jects-space-3'
  | '--jects-space-4'
  | '--jects-space-5'
  | '--jects-space-6'
  | '--jects-space-7'
  | '--jects-space-8'
  | '--jects-space-9'
  | '--jects-space-10'
  | '--jects-space-11'
  | '--jects-space-12'
  | '--jects-radius'
  | '--jects-font-family'
  | '--jects-font-family-mono'
  | '--jects-font-size-xs'
  | '--jects-font-size-sm'
  | '--jects-font-size-md'
  | '--jects-font-size-lg'
  | '--jects-font-size-xl'
  | '--jects-font-size-2xl'
  | '--jects-font-weight-normal'
  | '--jects-font-weight-medium'
  | '--jects-font-weight-semibold'
  | '--jects-font-weight-bold'
  | '--jects-shadow-sm'
  | '--jects-shadow-md'
  | '--jects-shadow-lg'
  | '--jects-z-dropdown'
  | '--jects-z-sticky'
  | '--jects-z-overlay'
  | '--jects-z-modal'
  | '--jects-z-popover'
  | '--jects-z-tooltip'
  | '--jects-duration-fast'
  | '--jects-duration-normal'
  | '--jects-duration-slow';

/** Tier-2 semantic token names (without prefix). */
export type JectsSemanticName =
  | 'background'
  | 'foreground'
  | 'card'
  | 'card-foreground'
  | 'popover'
  | 'popover-foreground'
  | 'primary'
  | 'primary-foreground'
  | 'secondary'
  | 'secondary-foreground'
  | 'muted'
  | 'muted-foreground'
  | 'accent'
  | 'accent-foreground'
  | 'destructive'
  | 'destructive-foreground'
  | 'success'
  | 'success-foreground'
  | 'warning'
  | 'warning-foreground'
  | 'border'
  | 'input'
  | 'ring';

/** Calm CMYK palette token names (without prefix). */
export type JectsCmykName =
  | 'cmyk-cyan'
  | 'cmyk-magenta'
  | 'cmyk-yellow'
  | 'cmyk-key'
  | 'cmyk-cyan-soft'
  | 'cmyk-magenta-soft'
  | 'cmyk-yellow-soft'
  | 'cmyk-key-soft';

/** Scale/scalar token names (without prefix). */
export type JectsScaleName =
  | 'space-0'
  | 'space-1'
  | 'space-2'
  | 'space-3'
  | 'space-4'
  | 'space-5'
  | 'space-6'
  | 'space-7'
  | 'space-8'
  | 'space-9'
  | 'space-10'
  | 'space-11'
  | 'space-12'
  | 'radius'
  | 'font-family'
  | 'font-family-mono'
  | 'font-size-xs'
  | 'font-size-sm'
  | 'font-size-md'
  | 'font-size-lg'
  | 'font-size-xl'
  | 'font-size-2xl'
  | 'font-weight-normal'
  | 'font-weight-medium'
  | 'font-weight-semibold'
  | 'font-weight-bold'
  | 'shadow-sm'
  | 'shadow-md'
  | 'shadow-lg'
  | 'z-dropdown'
  | 'z-sticky'
  | 'z-overlay'
  | 'z-modal'
  | 'z-popover'
  | 'z-tooltip'
  | 'duration-fast'
  | 'duration-normal'
  | 'duration-slow';

/** The CSS custom-property prefix used by every token. */
export const TOKEN_PREFIX = '--jects-' as const;

/** All Tier-2 semantic names. */
export const SEMANTIC_TOKENS = ["background","foreground","card","card-foreground","popover","popover-foreground","primary","primary-foreground","secondary","secondary-foreground","muted","muted-foreground","accent","accent-foreground","destructive","destructive-foreground","success","success-foreground","warning","warning-foreground","border","input","ring"] as const;

/** Calm CMYK categorical palette names. */
export const CMYK_TOKENS = ["cmyk-cyan","cmyk-magenta","cmyk-yellow","cmyk-key","cmyk-cyan-soft","cmyk-magenta-soft","cmyk-yellow-soft","cmyk-key-soft"] as const;

/** Chart series ramp names (data-1 … data-8). */
export const DATA_TOKENS = ["data-1","data-2","data-3","data-4","data-5","data-6","data-7","data-8"] as const;

/** Scale token names. */
export const SCALE_TOKENS = ["space-0","space-1","space-2","space-3","space-4","space-5","space-6","space-7","space-8","space-9","space-10","space-11","space-12","radius","font-family","font-family-mono","font-size-xs","font-size-sm","font-size-md","font-size-lg","font-size-xl","font-size-2xl","font-weight-normal","font-weight-medium","font-weight-semibold","font-weight-bold","shadow-sm","shadow-md","shadow-lg","z-dropdown","z-sticky","z-overlay","z-modal","z-popover","z-tooltip","duration-fast","duration-normal","duration-slow"] as const;

/** Default (light) OKLCH triplet values for the house theme. */
export const LIGHT_DEFAULTS: Record<string, string> = {
  "background": "1 0 0",
  "foreground": "0.145 0.006 272",
  "card": "1 0 0",
  "card-foreground": "0.145 0.006 272",
  "popover": "1 0 0",
  "popover-foreground": "0.145 0.006 272",
  "primary": "0.21 0.008 272",
  "primary-foreground": "0.985 0.001 272",
  "secondary": "0.967 0.003 272",
  "secondary-foreground": "0.21 0.008 272",
  "muted": "0.967 0.003 272",
  "muted-foreground": "0.48 0.018 272",
  "accent": "0.967 0.003 272",
  "accent-foreground": "0.21 0.008 272",
  "destructive": "0.48 0.245 27.3",
  "destructive-foreground": "0.985 0 0",
  "success": "0.62 0.12 160",
  "success-foreground": "0.985 0.001 272",
  "warning": "0.80 0.11 92",
  "warning-foreground": "0.21 0.008 272",
  "border": "0.92 0.005 272",
  "input": "0.92 0.005 272",
  "ring": "0.705 0.02 272"
};

/** Dark OKLCH triplet values for the house theme. */
export const DARK_DEFAULTS: Record<string, string> = {
  "background": "0.145 0.006 272",
  "foreground": "0.985 0.001 272",
  "card": "0.205 0.008 272",
  "card-foreground": "0.985 0.001 272",
  "popover": "0.205 0.008 272",
  "popover-foreground": "0.985 0.001 272",
  "primary": "0.92 0.004 272",
  "primary-foreground": "0.21 0.008 272",
  "secondary": "0.27 0.01 272",
  "secondary-foreground": "0.985 0.001 272",
  "muted": "0.27 0.01 272",
  "muted-foreground": "0.705 0.018 272",
  "accent": "0.27 0.01 272",
  "accent-foreground": "0.985 0.001 272",
  "destructive": "0.704 0.191 22",
  "destructive-foreground": "0.985 0 0",
  "success": "0.65 0.13 160",
  "success-foreground": "0.145 0.006 272",
  "warning": "0.80 0.11 92",
  "warning-foreground": "0.205 0.008 272",
  "border": "0.27 0.01 272",
  "input": "0.27 0.01 272",
  "ring": "0.556 0.02 272"
};

/** Build a token reference, e.g. tokenVar('primary') => 'var(--jects-primary)'. */
export function tokenVar(name: string): string {
  return `var(${TOKEN_PREFIX}${name})`;
}

/** Build an oklch() color from a triplet token, e.g. oklch('primary', 0.5). */
export function oklchToken(name: string, alpha?: number): string {
  const ref = tokenVar(name);
  return alpha === undefined ? `oklch(${ref})` : `oklch(${ref} / ${alpha})`;
}
