// Generate theme CSS from the @jects/tokens JSON source of truth.
// Emits base (light), dark, high-contrast (light+dark), and two branded presets,
// all inside the @layer cascade so consumer overrides win.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const tokensPkg = resolve(root, '../tokens');
const tokens = JSON.parse(readFileSync(resolve(tokensPkg, 'src/tokens.json'), 'utf8'));
const PREFIX = '--jects-';

const outDir = resolve(root, 'dist/css');
mkdirSync(outDir, { recursive: true });

const LAYERS =
  '@layer jects.reset, jects.tokens, jects.base, jects.components, jects.utilities;';

const decls = (map, indent = '    ') =>
  Object.entries(map)
    .map(([k, v]) => `${indent}${PREFIX}${k}: ${v};`)
    .join('\n');

// Theme-invariant groups (cmyk, data, scale) live in the tokens layer too.
// CMYK names are prefixed --jects-cmyk-* to namespace the categorical palette.
const cmykPrefixed = Object.fromEntries(
  Object.entries(tokens.cmyk).map(([k, v]) => [`cmyk-${k}`, v]),
);
const invariant = { ...cmykPrefixed, ...tokens.data, ...tokens.scale };

// ---- base.css : reset + tokens(light) + base element styles ---------------
const base = `/* AUTO-GENERATED by scripts/build-theme.mjs — do not edit. */
/* Jects UI — base theme (House style: ${tokens.$meta.name}). Light on :root. */
${LAYERS}

@layer jects.reset {
  *, *::before, *::after { box-sizing: border-box; }
  .jects-scope, [data-jects-scope] { font-family: var(${PREFIX}font-family); }
}

@layer jects.tokens {
  :root {
    /* Tier-2 semantic (light) */
${decls(tokens.semantic.light)}

    /* Calm CMYK palette + data ramp + scales (theme-invariant) */
${decls(invariant)}

    /* Derived radii cascade from a single --jects-radius */
    ${PREFIX}radius-sm: calc(var(${PREFIX}radius) - 4px);
    ${PREFIX}radius-md: calc(var(${PREFIX}radius) - 2px);
    ${PREFIX}radius-lg: var(${PREFIX}radius);
    ${PREFIX}radius-xl: calc(var(${PREFIX}radius) + 4px);
  }
}

@layer jects.base {
  .jects-scope, [data-jects-scope] {
    background: oklch(var(${PREFIX}background));
    color: oklch(var(${PREFIX}foreground));
    font-family: var(${PREFIX}font-family);
    font-size: var(${PREFIX}font-size-md);
  }
}
`;
writeFileSync(resolve(outDir, 'base.css'), base);

// ---- dark.css : overrides on .jects-dark or [data-jects-theme=dark] -------
const dark = `/* AUTO-GENERATED — Jects UI dark theme overrides. */
@layer jects.tokens {
  .jects-dark,
  [data-jects-theme='dark'] {
${decls(tokens.semantic.dark)}
  }
}
`;
writeFileSync(resolve(outDir, 'dark.css'), dark);

// ---- high-contrast (light + dark) -----------------------------------------
// Push foreground/background apart, strengthen borders & ring.
const hcLight = {
  ...tokens.semantic.light,
  foreground: '0 0 0',
  'muted-foreground': '0.30 0.01 272',
  border: '0.65 0.01 272',
  input: '0.55 0.01 272',
  ring: '0.45 0.03 272',
  primary: '0.15 0.01 272',
};
const hcDark = {
  ...tokens.semantic.dark,
  foreground: '1 0 0',
  'muted-foreground': '0.85 0.01 272',
  border: '0.55 0.01 272',
  input: '0.6 0.01 272',
  ring: '0.75 0.03 272',
};
const hc = `/* AUTO-GENERATED — Jects UI high-contrast themes. */
@layer jects.tokens {
  .jects-hc,
  [data-jects-theme='light-hc'] {
${decls(hcLight)}
  }
  .jects-dark.jects-hc,
  [data-jects-theme='dark-hc'] {
${decls(hcDark)}
  }
}
`;
writeFileSync(resolve(outDir, 'high-contrast.css'), hc);

// ---- Stockholm-like (minimalist): neutral, near-zero chroma, tight radius --
const stockholm = {
  ...tokens.semantic.light,
  primary: '0.22 0.004 272',
  'primary-foreground': '0.99 0 0',
  ring: '0.60 0.01 272',
  radius: undefined,
};
delete stockholm.radius;
const stockholmCss = `/* AUTO-GENERATED — Jects UI "Stockholm" minimalist preset. */
@layer jects.tokens {
  .jects-theme-stockholm,
  [data-jects-theme='stockholm'] {
${decls(stockholm)}
    ${PREFIX}radius: 0.25rem;
    ${PREFIX}shadow-sm: none;
    ${PREFIX}shadow-md: 0 1px 2px 0 oklch(0 0 0 / 0.06);
  }
}
`;
writeFileSync(resolve(outDir, 'stockholm.css'), stockholmCss);

// ---- Material-like : vivid primary, larger radius, elevation --------------
const material = {
  ...tokens.semantic.light,
  primary: '0.55 0.18 265',
  'primary-foreground': '0.99 0 0',
  ring: '0.55 0.18 265',
  accent: '0.95 0.03 265',
  'accent-foreground': '0.30 0.10 265',
};
const materialCss = `/* AUTO-GENERATED — Jects UI "Material" preset. */
@layer jects.tokens {
  .jects-theme-material,
  [data-jects-theme='material'] {
${decls(material)}
    ${PREFIX}radius: 1rem;
    ${PREFIX}shadow-md: 0 2px 4px oklch(0 0 0 / 0.2), 0 1px 10px oklch(0 0 0 / 0.12);
  }
}
`;
writeFileSync(resolve(outDir, 'material.css'), materialCss);

// ---- all.css : convenience bundle -----------------------------------------
const all = `/* AUTO-GENERATED — all Jects themes. */
@import './base.css';
@import './dark.css';
@import './high-contrast.css';
@import './stockholm.css';
@import './material.css';
`;
writeFileSync(resolve(outDir, 'all.css'), all);

console.log('theme: wrote base/dark/high-contrast/stockholm/material/all CSS');
